services:

  - type: web
    name: test
    runtime: node

    buildCommand: |
      npm install
      apt-get update
      apt-get install -y chromium-browser
      sudo apt-get install google-chrome-stable

    startCommand: node index.js