services:

  - type: web
    name: my-app 
    runtime: nodejs
    nodeVersion: "18"

    buildCommand: npm install
    startCommand: node index.js
    
    envVars:
      CHROME_BIN: /usr/bin/google-chrome-stable