services:

  - type: web
    name: my-app 
    runtime: nodejs
    nodeVersion: "18"

    buildCommand: |
      npm install
      apt-get update
      apt-get install -y chromium-browser
      sudo apt-get install google-chrome-stable

    startCommand: node index.js
    
    addons:
      chrome: stable